---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    expose:
        - "2181"
    ports:
        - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_SYNC_LIMIT: 2

  broker:
    image: confluentinc/cp-kafka:5.5.0
    links:
        - zookeeper
    expose:
        - "2183"
    ports:
        - "9092:9092"
        - "29092:29092"
    environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_AUTO_CREATE_TOPICS: "true"
        KAFKA_NUM_PARTITIONS: 1
        KAFKA_BROKER_ID: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        JMX_PORT: 2183
        KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
        CONFLUENT_METRICS_ENABLE: 'false'
    depends_on:
        - zookeeper
  
  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.0
    links:
        - zookeeper
        - broker
    expose:
        - "8081"
    ports:
        - "8081:8081"
    environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
        SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
        SCHEMA_REGISTRY_DEBUG: "false"
    depends_on:
        - zookeeper
        - broker

  telegraf:
    image: telegraf:1.19.3
    depends_on:
      - broker
      - influxdb
    links:
      - broker
      - influxdb
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influxdb:
    image: influxdb:2.0.8
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: my-user
      DOCKER_INFLUXDB_INIT_PASSWORD: my-password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token
      V1_AUTH_USERNAME: my-user
      V1_AUTH_PASSWORD: my-password
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'

  kafkacat:
    image: edenhill/kafkacat:1.5.0
    container_name: kafkacat
    entrypoint: 
      - /bin/sh 
      - -c 
      - |
        apk add jq; 
        while [ 1 -eq 1 ];do sleep 60;done